name: Genrate Student Repository

on:
  push:
    branches:
      - main  

jobs:
  generate_student_repo:
    name: Generate student repository
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.PAT_TOKEN }} # FIXME: secret name
      REPO_NAME: "student-repo" # FIXME
      USERNAME: "sebuw" # FIXME: 

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10' 
    
    - name: Install dependencies if any
      run: |
        python -m pip install --upgrade pip
    
    - name: Run Python script
      run: python generate_task_repo.py

    - name: Set up Git config
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"

    - name: Check if the repository exists
      id: check_repo
      run: |
        gh repo view ${USERNAME}/${REPO_NAME} || echo "::set-output name=exists::false"

    - name: Create repository if it doesn't exist
      id: create_repo
      if: steps.check_repo.outputs.exists == 'false'
      run: |
        gh repo create ${USERNAME}/${REPO_NAME} --private

    - name: Copy task_repo and push to the repository
      run: |
        git clone --depth 1 https://${GH_TOKEN}@github.com/${USERNAME}/${REPO_NAME}.git dest_repo
        cp -r student_repo/ dest_repo/
        cd dest_repo
        pwd
        ls -alh
        git add .
        git commit -m "Initialized student repository"
        git push -f origin main
        # git push destination --all
        # git push destination --tags
    - name: Cleanup
      run: |
        rm -rf dest_repo
