name: Genrate Student Repository

on:
  push:
    branches:
      - main  # Adjust this to your main branch name

jobs:
  generate_student_repo:
    name: Generate student repository
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      
      - name: Run Python script
        run: python generate_task_repo.py  # Replace with your actual script name


      - name: Check if repository exists
        run: |
          pwd
          USER="sebuw"
          REPO_NAME="test-task"
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" -u ${{ secrets.PAT_TOKEN }} https://api.github.com/repos/$USER/$REPO_NAME)
          
          if [ $STATUS -eq 200 ]; then
            echo "Repository exists."
          else
            echo "Repository does not exist. Creating..."
            curl -u ${{ secrets.PAT_TOKEN }} -H "Accept: application/vnd.github.v3+json" -d '{"name":"'"$REPO_NAME"'", "private": true}' https://api.github.com/user/repos
          fi

      - name: Set up Git user
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Clone newly created repository
        run: |
          git clone https://github.com/${{ github.actor }}/test-task.git
          cd test-task  # Change to the cloned repository directory
  
      - name: Clear existing contents (if any)
        run: |
          git rm -r .

      - name: Copy contents of dest_dir
        run: |
          cp -r task_repo/* .

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Update from dest_dir"
          git push -u origin main
