name: Create and Copy Task Repo

on:
  push:
    branches:
      - main

jobs:
  create-and-copy:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.PAT_TOKEN }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Git
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"

    - name: Check if the repository exists
      id: check_repo
      run: |
        REPO_NAME="your-private-repo"
        gh repo view sebuw/${REPO_NAME} || echo "::set-output name=exists::false"

    - name: Create repository if it doesn't exist
      id: create_repo
      if: steps.check_repo.outputs.exists == 'false'
      run: |
        REPO_NAME="your-private-repo"
        gh repo create sebuw/${REPO_NAME} --private

    - name: Copy task_repo and push to the repository
      run: |
        REPO_NAME="your-private-repo"
        DEST_REPO_URL="https://github.com/sebuw/${REPO_NAME}.git"
        git clone --depth 1 https://github.com/sebuw/${REPO_NAME}.git cloned_repo
        

    - name: Cleanup
      run: |
        rm -rf cloned_repo
