name: Copy Task to Private Repo

on:
  push:
    branches:
      - main  # Change this to your default branch name

jobs:
  copy-task:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"

    - name: Check if private repo exists
      id: check_repo
      run: |
        REPO_NAME="your-private-repo"  # Change this to your desired private repo name
        gh repo view $REPO_NAME || echo "::set-output name=repo_exists::false"

    - name: Create private repo if not exists
      if: steps.check_repo.outputs.repo_exists == 'false'
      run: |
        REPO_NAME="your-private-repo"  # Change this to your desired private repo name
        gh repo create $REPO_NAME --private
        echo "::set-output name=repo_url::$(gh repo view $REPO_NAME --json html_url --template '{{.html_url}}')"

    - name: Copy and push task_repo to private repo
      run: |
        REPO_NAME="your-private-repo"  # Change this to your desired private repo name
        git remote add private_repo ${{ steps.check_repo.outputs.repo_url }}
        git push private_repo HEAD:main
